### ISSUE TITLE
Running GPM locally

### ISSUE THREAD

**Issue by jicowan** [sighupio/gatekeeper-policy-manager#1]
The README says that you can run the container for GPM locally and that it will try to read the kubeconfig.  I'm trying to run this against an EKS server running OPA/Gatekeeper.  When viewing the constraints, I get the following 500 error: 
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Is there a way to pass it the kubeconfig as an environment variable?

The container logs indicate that it can't find the kubeconfig: 
```
config.load_kube_config()
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 739, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 701, in _get_kube_config_loader_for_yaml_file
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

**Comment by angelbarrera92** [comment]
Hi @jicowan! 

Can you paste us what is the command you used to run GPM container locally?

Thanks!

**Comment by ralgozino** [comment]
Hello @jicowan 

Maybe we should improve a little the docs, the running in local mode is more intended to be used while developing or running directly the python app.

Anyway, I can see how running directly the container locally could make sense in some cases. You probably are not mounting your kube-config to the container. Assuming that your kube-config is in `~/.kube/config` the command to run the container locally would be:

```bash
docker run -v ~/.kube/config:/root/.kube/config -p 8080:8080 quay.io/sighup/gatekeeper-policy-manager:0.1
```

Then you can access the app on HTTP://localhost:8080/

We should probably add that to the README.

Let us know how that goes!
Regards,

**Comment by jicowan** [comment]
That makes sense @ralgozino.  I'll try mounting the kubeconfig folder.  Thanks!

**Comment by ralgozino** [comment]
Thank you for reaching out! I hope you find GPM useful.

P.S. I've added the instructions to the README in this commit https://github.com/sighupio/gatekeeper-policy-manager/commit/2566aba679fa25d60810e843f2bbc122e45136ae

**Comment by jicowan** [comment]
@ralgozino It's pretty slick.  I like being able to view the rego within a nice UI.  It's minor nit, but if you're running Gatekeeper without any policies like I was initially, GPM displays a weird error when you try looking at the constraint templates and the constraints.  Displaying more a user friendly message, like "Gatekeeper has no configured templates" might be a little better.
