### ISSUE TITLE
Does it support exporting violations?

### ISSUE THREAD

**Issue by swapnild2111** [sighupio/gatekeeper-policy-manager#108]
As one of the requirement, we need to alert product teams regarding constraint violations. We are planning to alert via Ms Teams channels & emails. So looks for consolidated data categorized product wise. We can do that if there is a way to get all violations listed somewhere. Do you think its possible? Help please 🙂

**Comment by ralgozino** [comment]
Hi there!

This seems like a job for Gatekeeper itself, I see that you've commented on this issue already:

https://github.com/open-policy-agent/gatekeeper/issues/580

It is not clear to me what you need from GPM though. Could you please explain better? If I'm getting it right you'd like an endpoint to request all violations, right? You can already do that using the Kubernetes API, take a look at GPM's source code to see how we do it.

**Comment by swapnild2111** [comment]
Hello @ralgozino 
I have configured gatekeeper to run every 4 hours in dryrun mode.
So before I start running it in real deny mode, I want to inform my product teams about their current deployment issues/violations. Those are listed under status of each constraint.

I was thinking if I get list of violations list from all constraints, I will apply proper filters on that list & notify product teams about their issues & ask them to correct it.

Hope I was able to explain :) This is just a question, may not be directly related to GPM, but since you have constraints tab on UI, you might have such violations list in backend which can be saved.

**Comment by ralgozino** [comment]
I think now I understand, GPM does not provide a feature to export all the violations nor an API endpoint to get them. As I said in my first comment, you can get the list from the Kubernetes API itself as we do, check the source code.

Please notice that Gatekeeper doesn't store all the violations on the status field. It just stores the first 20 by default.

**Comment by ralgozino** [comment]
Hi @swapnild2111 
I hope you are doing well, we've just pushed an update to GPM to add a "report" view of the violations. You'll find a new entry on the constraints view to open the report.

You can test the new feature by switching to the `unstable` image tag or wait for an official release. 

If you test it, let us know what you think!
Regards,
Ramiro.

**Comment by crouth-redge** [comment]
@ralgozino  Is it possible to have the report produce a CSV - or a report with all constraints whether they passed or fail? Right now it only reports violations, but for an audit you need _all results_ in the report. Not just violations.
