### ISSUE TITLE
Need small help reg UI modification

### ISSUE THREAD

**Issue by swapnild2111** [sighupio/gatekeeper-policy-manager#111]
Hello Team,
I tried this tool in my k8s cluster with your prepared docker image. It works awesome! :)

I have 6 k8s clusters ( & increasing ) and I don't really want to implement this dashboard per cluster.
I was thinking to modify your UI and add my cluster list as drop down to select to tweak data. Not sure how difficult that would be.

So I have two questions - 
1. I am not sure about licensing part, is it ok to modify your UI? I need to include your code & licence file in my repo for it. Never done before.
2. If you have any other solution for this scenario?

Thank you :)

**Comment by ralgozino** [comment]
Hello!

Regarding the licensing question, You can check the [LICENSE](https://github.com/sighupio/gatekeeper-policy-manager/blob/master/LICENSE) file, where you'll find some pointers. We should probably write some contribution guidelines with more details. You can then open a PR to the project If you would like us to consider merging the feature.

For the multi-cluster scenario, one option is to run GPM locally so it will pick-up your local `kubeconfig` file, in this manner if you switch context from one cluster to another GPM will show you the status of the cluster you are pointing to. Refreshing the page should be enough.

**Comment by swapnild2111** [comment]
Thank you @ralgozino 👍 

We have a separate cluster to hold devops platform offerings. So I will get deploying GPM there. Then as you said, I will modify UI to select my product team clusters & update page. will check licence file & feature request if things looks more generic. :)

**Comment by ralgozino** [comment]
Hi @swapnild2111 
I hope you are doing well, we've just pushed an update to GPM to add multi-cluster support to the UI. You can test the new feature by switching to the `unstable` image tag or wait for an official release. You'll see a dropdown on almost all the pages to switch the current cluster.

If you test it, let us know what you think!
Regards,
Ramiro.

**Comment by swapnild2111** [comment]
I will check soon :) sorry never got notification for this.
