### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by cheungaryk** [sighupio/gatekeeper-policy-manager#123]
While using the GPM UI (v0.4.1), I have noticed that Constraint has been mispelled:

<img width="565" alt="Screen Shot 2021-02-26 at 2 04 21 PM" src="https://user-images.githubusercontent.com/10934908/109360197-a2859880-783b-11eb-8cdc-712f0769e1f7.png">

I did a search on the source code and found where the spelling error is located:
https://github.com/sighupio/gatekeeper-policy-manager/blob/b7b1775d5eed904dc9d77300d08d8e8794bf32dd/app/templates/base.html#L31

I also noticed the same spelling errors in these places:
https://github.com/sighupio/gatekeeper-policy-manager/blob/32b495ced0bf32cd4d88e96aa17241db82041704/README.md#L7

https://github.com/sighupio/gatekeeper-policy-manager/blob/1b3ef5c8c011fb02f6bd2f1e8f9855219ce09a5d/app/app.py#L159

This is probably an easy fix, and the priority is low since I don't think it affects any functionality, but now I can't unsee it and it has been bothering me since 😛

**Comment by ralgozino** [comment]
Well.. this is a little embarrassing 😊  thank you for letting us know!

**Comment by ralgozino** [comment]
Fixed on `unstable` tag. The fix will be included in the next release.

Thanks!
