### ISSUE TITLE
OIDC Error: invalid_client

### ISSUE THREAD

**Issue by DrackThor** [sighupio/gatekeeper-policy-manager#165]
Hi team,

I tried to use the new OIDC feature and got the following error: OIDC Error: invalid_client
I managed to connect GPM to my IDP, be redirected, give consent and get an authorization_code.
However, when I get redirected to GPM with the endpoint:
```url
https://<my-domain>/oidc-auth?code=<auth_code>
&iss=<my-idp>%3A443%2Fauth%2Foauth2%2Fuser
&state=9oz60Lx7ENYgRnPR
&client_id=gatekeeper-policy-manager
```
I get the mentioned error, but I cannot find additional info in the logs (GPM_LOG_LEVEL=DEBUG).

maybe this has sth to do with not setting the ```userinfo_endpoint_method``` attribute in ```ProviderConfiguration``` - [docs](https://flask-pyoidc.readthedocs.io/en/stable/api.html#flask_pyoidc.provider_configuration.ProviderConfiguration.userinfo_endpoint_method)? Although I'm not sure if requesting userinfo is intended in the first place?

**Comment by ralgozino** [comment]
Hi @DrackThor !

Are you having this error after an update or is this the first time you are trying out GPM?

It's kinda strange you don't get to see any error in the logs, could you please try:
- forcing a logout: https://<my-domain>/logout and see if then you can login
- cleaning the browser cache a cookies
- setting the GPM_OIDC_USERINFO_ENDPOINT env var

If you could give us more details (like GPM version, Kubernetes version, what IDP you are using, etc), that might help us the debugging

Thansk!

**Comment by DrackThor** [comment]
This error occurs after a fresh installation.
I'm using the manifest files directly and applying them using kubectl apply.
Using a logout did not work, although the logout appeared to work: 
Cleaning the browser cache and cookies did not change anything.
GPM_OIDC_USERINFO_ENDPOINT is set.

GPM Version: v0.4.2
K8s Version: 1.19.10
IDP: ForgeRock AM (I will try it with KeyCloak 11.0.3 also)

Can you probably give me an example of how you configured your oidc client on the IDP?

**Comment by DrackThor** [comment]
I was able to get OIDC running with KeyCloak, therefore I assume the original problem is based on some internal misconfiguration of my other IDP.

**Comment by ralgozino** [comment]
Thanks for the heads-up! I'm glad you got it working :)
