### ISSUE TITLE
node_modules folder missing

### ISSUE THREAD

**Issue by hkerma** [sighupio/gatekeeper-policy-manager#247]
Hello,
I'm running GPM locally, directly through Python. However, when I want to access the webpage, I'm missing the "node_modules" folder, in "static". Thus, all the CSS and JS are missing. I suppose it is supposed to be generated at runtime, but I'm not familiar with web environment.

Is there a way to generate that folder while running GPM with Python ?

**Comment by ralgozino** [comment]
Hi @hkerma 

You need to run `npm install` inside the `app/static` folder. I'll update the development part of the README with these instructions. Thanks for pointing it out.

If you want to just run the app locally and you don't want to develop or modify anything, it will be much simpler to use the docker image, see [this part of the readme](https://github.com/sighupio/gatekeeper-policy-manager#running-locally)

Let me know how it goes...

PS: Tomorrow will be releasing v0.5.0, just for you information ;-)

**Comment by hkerma** [comment]
Hello @ralgozino 
Thank you for that very quick answer. It worked perfectly.
I'll update to 0.5.0 tomorrow then 👍

**Comment by ralgozino** [comment]
Thanks for the confirmation. Closing this issue now, please feel free to contact us again if you find any issues :)
