### ISSUE TITLE
OOM Kill occurred in v0.5.0

### ISSUE THREAD

**Issue by Darwin014** [sighupio/gatekeeper-policy-manager#255]
Hi,
I'm using EKS and I'm getting OOM Kill errors in v0.5.0. No OOM Kill errors in v0.4.2.

Sep  8 06:22:08 kernel: Tasks state (memory values in pages):
Sep  8 06:22:08 kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Sep  8 06:22:08 kernel: [  22826]     0 22826      242        1    28672        0          -998 pause
Sep  8 06:22:08 kernel: [  22954]   999 22954     6649     5658    86016        0           984 gunicorn
Sep  8 06:22:08 kernel: [   2908]   999  2908    52015    18550   303104        0           984 gunicorn
Sep  8 06:22:08 kernel: [   2979]   999  2979    30079    15485   270336        0           984 gunicorn
Sep  8 06:22:08 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=a8638b0128b07b17bd22a5694da752d1c3b018b6237bdee4db906df6e4d1225d,mems_allowed=0,oom_memcg=/kubepods/burstable/podcb4794b7-954b-4831-81cf-403d83ad22a4,task_memcg=/kubepods/burstable/podcb4794b7-954b-4831-81cf-403d83ad22a4/a8638b0128b07b17bd22a5694da752d1c3b018b6237bdee4db906df6e4d1225d,task=gunicorn,pid=2908,uid=999
Sep  8 06:22:08 kernel: Memory cgroup out of memory: Killed process 2908 (gunicorn) total-vm:208060kB, anon-rss:64296kB, file-rss:9904kB, shmem-rss:0kB, UID:999 pgtables:296kB oom_score_adj:984
Sep  8 06:22:08 kubelet: I0908 06:22:08.641656    4813 oom_watcher_linux.go:76] Got sys oom event: &{2908 gunicorn 2021-09-08 06:22:04.485962201 +0000 UTC m=+353595.277360527 / / }
Sep  8 06:22:08  kernel: oom_reaper: reaped process 2908 (gunicorn), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
^C

**Comment by ralgozino** [comment]
Hi @Darwin014 !

Can I ask you for some details?

1. how did you install GPM? did you use the customize manifests or the new helm chart?
2. How many constraints templates, constraints and violations do you have in your cluster?
3. In which mode are you running GPM? are you using it to see the status of the cluster where it is deployed?
4. Any chance of seeing the memory usage of the pod for v0.5.0? does it look as a memory leak or  it is just using a little more memory?
5. Can you try increasing the memory limit of the pod?

Thanks!

**Comment by Darwin014** [comment]
Hi @ralgozino 
I used the helm chart and tested it with the default settings.
There were 2 templates, and when I increased the memory limit to 256M, no OOM error occurred.

Thanks for your help!

**Comment by ralgozino** [comment]
great! I'm glad you could fix it. Thanks for letting us know :-)
