### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by chelomontilla** [sighupio/gatekeeper-policy-manager#259]
Hello,
I'm trying gatekeeper and found this great project to easily check config and violations.
I've deployed it in kubernetes using the helm chart and the CPU consumption is quite high with the latest relase version.
This is one pod with version 0.5.0
[https://ibb.co/PYSHYHn](https://ibb.co/PYSHYHn)

This is one pod with version 0.4.2
[https://ibb.co/xfFfK6x](https://ibb.co/xfFfK6x)

Let me know if I can collaborates somehow on solving the issue.
Thanks in advance

**Comment by ralgozino** [comment]
Hola @chelomontilla !

Nice finding, let me do some tests and I'll come back to you.

Just for my curiosity, is GPM v0.5.0 working as expected besides the high CPU usage? Do you see something in the logs? Can you try rising the log level to `DEBUG` and see if you find anything strange?

Thanks!

**Comment by ralgozino** [comment]
I can't replicate this locally. The CPU usage for `v0.5.0` is under 1 milli core while GPM is idling:

```
 $ kubectl top pod -n gatekeeper-system
NAME                                             CPU(cores)   MEMORY(bytes)
gatekeeper-audit-fbc6596f7-79pbj                 12m          71Mi
gatekeeper-controller-manager-5f64c4d565-pnrjg   4m           51Mi
gatekeeper-controller-manager-5f64c4d565-sl4mz   5m           61Mi
gatekeeper-controller-manager-5f64c4d565-v4gkr   9m           62Mi
gatekeeper-policy-manager-7dfbd5cf55-2n2fk       1m           107Mi
```

![image](https://user-images.githubusercontent.com/6362698/133818797-259aa059-9751-4d11-8ae6-983aa00fc71d.png)

Is there something special about your environment @chelomontilla that we should take into account?

**Comment by chelomontilla** [comment]
Hello,
I've just checked and works perfectly. The high CPU consumption was due the memory requests and limits. Requests and limits for memory were configured with 128Mi and didn't see it was reaching limits. I've reconfigured the pod resources with 156Mi requests and 192Mi and the cpu is pretty low right now.

Thanks a lot
