### ISSUE TITLE
[Request] Make helm chart available at https://sighupio.github.io/gatekeeper-policy-manager

### ISSUE THREAD

**Issue by boeboe** [sighupio/gatekeeper-policy-manager#281]
Most chart offer a helm repo. Github offers a nice way to do this with github pages.

Chart releaser offers a nice way to automate this process once gitpages are enabled on this repo
https://github.com/helm/chart-releaser

**Comment by HenriWilliams** [comment]
+1

**Comment by brsolomon-deloitte** [comment]
What's the timeline on that roadmap @ralgozino ?

**Comment by ralgozino** [comment]
Hi @brsolomon-deloitte , there's no ETA for this feature at the moment
