### ISSUE TITLE
Error while loading /constraints

### ISSUE THREAD

**Issue by jecnua** [sighupio/gatekeeper-policy-manager#3]
Hi all,

I have an issue while running GPM.
I am trying to run GPM in a cluster where I just installed gatekeeper (mostly to run the audit component for now).
I created a constraint template and tested in the cluster. I can see the violation inside the k8s object correctly.

```
  Total Violations:  298
  Violations:
    Enforcement Action:  dryrun
    Kind:                ReplicaSet
    Message:             Rejecting "ReplicaSet/xxx" for not specifying a livenessProbe
    Name:                xxx-xxx
    Namespace:           backup
    Enforcement Action:  dryrun
    Kind:                ReplicaSet
    Message:             Rejecting "ReplicaSet/xxx-xxx" for not specifying a livenessProbe
    Name:                xxx-xxx
    Namespace:           backup
    Enforcement Action:  dryrun
    Kind:                ReplicaSet
    Message:             Rejecting "ReplicaSet/xxx-xxx" for not specifying a livenessProbe
    Name:                xxx-xxx
    Namespace:           backup
[...]
```

Now, while running GPM, langing page and /constrainttemplates/ work correctly (I can see the ct) but when I try to go to:

`/constraints`

I get:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

In the logs I can see the following error:

```
[2020-09-30 15:54:33,648] INFO in app: KUBERNETES_SERVICE_HOST found, assuming to be running inside Kubernetes cluster
[2020-09-30 15:54:33,661] ERROR in app: Exception on /constraints/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 36, in decorated_function
    return f(*args, **kwargs)
  File "./app.py", line 180, in get_constraints
    title="Constraints")
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/app/templates/constraints.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/app/templates/base.html", line 47, in top-level template code
    {% block content %}{% endblock %}
  File "/app/templates/constraints.html", line 52, in block "content"
    {% if constraint.spec.match.kinds %}
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'match'
```

I am using:
- GPM version 0.2
- Gatekeeper v3.1.1 
- k8s v1.18.8

Thank you for your time and the amazing job you are all doing 👍

**Comment by ralgozino** [comment]
Hi! Thanks for reaching out :) I'm sorry you are facing this issue.

Could you please confirm that your constraint doesn't have any match criteria defined?

In the meanwhile, I've pushed an updated image that should bypass this error. Could you please try using this docker image instead for GPM:
`quay.io/sighup/gatekeeper-policy-manager:0.3rc1`

Let me know if this works :)

**Comment by jecnua** [comment]
Hi @ralgozino,

Thanks for the fast reply. :) 

> I'm sorry you are facing this issue.

Do not worry, it's really me thanking you for the work.
Now about the issue: yes, I used your examples at:

```
fury-kubernetes-opa/katalog/gatekeeper/rules/constraints/must_have_liveness_probe.yml
fury-kubernetes-opa/katalog/gatekeeper/rules/templates/livenessprobe_template.yml
```

There is no match criteria. Also the new container `0.3rc1` works very well and I can load the constraints page:

![Gatekeeper_Policy_Manager_-_Constraints](https://user-images.githubusercontent.com/162194/94713544-d6b76480-0342-11eb-9d73-198153a0fb1f.png)

**Comment by ralgozino** [comment]
I'm glad to hear that! 
Thanks for the feedback, let us know if you find any other issue 🙂

**Comment by ralgozino** [comment]
Hi @jecnua 
Testing some stuff I remember your issue, and I think I know why your constraint didn't had a match criteria defined. You are probably using the constraints files directly from the module, but they are thought to be used using `kustomize`, if you take a look you'll find that in the same folder there's a [`kustomization.yaml` file](https://github.com/sighupio/fury-kubernetes-opa/blob/master/katalog/gatekeeper/rules/constraints/kustomization.yaml), that adds the match criteria to the constraints.

**Comment by jecnua** [comment]
Thank you for the heads up @ralgozino. Unfortunately here at the moment we don't use kustomize but only helm charts. I will however get the resulting json from the kustomize apply and move it in a chart. :)
I did notice someting however while testing. Some of the names of resources in https://github.com/sighupio/fury-kubernetes-opa/tree/master/katalog/gatekeeper/rules/templates overlap with https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/ (like for k8suniqueingresshost). I think would be a good idea to namespace the CRD names to avoid such conflicts since I expect people to also use gatekeeper-library more and more as it grows.

Thanks again for the ping.

**Comment by ralgozino** [comment]
Thanks for the feedback @jecnua , we'll discuss with the team what you pointed out. Let us know if you find any other improvements to be done or issues that we should know about!

**Comment by swapnild2111** [comment]
@jecnua Hello as per above discussion, am using `quay.io/sighup/gatekeeper-policy-manager:0.3rc1` however I still get error on constraints tab:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Other tabs work.

Can you please help?
