### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by cnwaldron** [sighupio/gatekeeper-policy-manager#4]
It would be really wonderful if GPM UI could be used in an environment without internet access. 

Thanks!

**Comment by ralgozino** [comment]
Hello @cnwaldron 
Could please try switching GPM image to `quay.io/sighup/gatekeeper-policy-manager:0.3rc2` and let me know if it works for you?

Thanks!

**Comment by cnwaldron** [comment]
Worked great! Thanks so much for the quick response and change! :)

**Comment by ralgozino** [comment]
Glad to hear that! Let us know if find something else that we can improve and thanks for the feedback 🙂
