### ISSUE TITLE
`Download violations report` in constraints tab is wrong when multicluster is enabled

### ISSUE THREAD

**Issue by czchen** [sighupio/gatekeeper-policy-manager#456]
Hi,

The `Download violations report` link in multicluster shall be `$host/api/v1/constraints/$cluster?report=html` to specifiy `$cluster`. However, it is `$host/api/v1/constraints?report=html` instead.

**Comment by ralgozino** [comment]
Thank you for the pointer @czchen, I've opened a PR to fix the problem.
