### ISSUE TITLE
Is there is a way to authenticate a user before he can enter the google policy manager UI

### ISSUE THREAD

**Issue by aditya-maven-2142** [sighupio/gatekeeper-policy-manager#706]

**Comment by aditya-maven-2142** [comment]
@ralgozino can you point me to a blog where one is using oidc authentication.

**Comment by ralgozino** [comment]
sorry, there's no blog post, you need to set the right environment variables to configure GPM to use OIDC and that's it.

set `GPM_AUTH_ENABLED` to `OIDC` and then all the other env vars that start with `GPM_OIDC`.

See the link to readme in my previous comment for more details.
