### ISSUE TITLE
Logout for oidc is http instead of https and CORS errors

### ISSUE THREAD

**Issue by goku007xx** [sighupio/gatekeeper-policy-manager#725]
I have added OIDC authentication using keycloak and it works fine with some tweaks which i had to do on the keycloak side regarding HTTP usage instead of HTTPS. Even though the app works fine, there are CORS errors appearing from the manifest.json file regarding which i have detailed below.

a) **Logout HTTP issue**:
    
<img width="1426" alt="Screenshot 2023-06-20 at 3 12 59 PM" src="https://github.com/sighupio/gatekeeper-policy-manager/assets/55452492/94724978-449e-4c7d-b634-a8b4a9614961">

As you can see above, the logout is successful and the session is removed from keycloak but the CORS issue arises from the 
logout GET request. The request's parameters are follows:<br />
1. `id_token_hint` : long_secret_value<br />
2. `post_logout_redirect _uri`: **http://gatekeeper-manager.xyz.com/logout** ( This should be HTTPS instead of HTTP )<br />
3. `state`: some_secret_value<br />
<br />

Initially the logout did not work but it works now after adding **http://gatekeeper-manager.xyz.com/logout** to the `Valid post logout redirect URIs` option in keycloak. After adding the url, logout works as shown in the picture but the CORS issue is arising from that which im assuming is from the HTTP url.(The reason now the HTTP url is working is from the fact that the cluster is behind a AWS ALB which redirects HTTP to HTTPS ). The below line could be where the `post_logout_redirect_uri` field is getting populated:<br />
`post_logout_redirect_uri = flask.request.url` in line 274 of src/flask_pyoidc/flask_pyoidc.py in the `Flask-pyoidc` repo.
<br />
b) **CORS issues from manifest.json**:

![image](https://github.com/sighupio/gatekeeper-policy-manager/assets/55452492/3cb8ef99-018b-47f9-b24e-c495e46a8360)

Every request which renders index.html also makes a request to manifest.json due to which there is a request to keycloak regarding some authentication which causes the CORS error. The console output error is given below.

`Access to manifest at 'https://keycloak.xyz.com/realms/realm_name/protocol/openid-connect/auth?client_id=****&response_type=code&scope=openid&redirect_uri=https%3A%2F%2Fgatekeeper-manager.xyz.com%2Foidc-auth&state=****&nonce=****' (redirected from 'https://gatekeeper-manager.xyz.com/manifest.json') from origin 'https://gatekeeper-manager.xyz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Removing the manifest can be a simple solution or something like this can also maybe fix this probably.(https://stackoverflow.com/questions/67259947/access-to-web-manifest-blocked-by-cors-policy) 

Any help regarding HTTP/CORS would be appreciated.

Versions used:
**GPM 1.0.3**

**Comment by ralgozino** [comment]
Hello @goku007xx 

May I ask you for the environment variables values that you are using to configure OIDC to try to replicate the issue? **please edit the sensible information**

**Comment by goku007xx** [comment]
`GPM_AUTH_ENABLED : "OIDC"`
`GPM_SECRET_KEY : <default-as-specified-in-docs>`
`GPM_PREFERRED_URL_SCHEME : https`
`GPM_OIDC_REDIRECT_DOMAIN : "https://gatekeeper-manager.xyz.com/"`
`GPM_OIDC_ISSUER : https://keycloak.xyz.com/realms/<realm-name>`
`GPM_OIDC_AUTHORIZATION_ENDPOINT : https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/auth`
`GPM_OIDC_JWKS_URI : https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/certs`
`GPM_OIDC_TOKEN_ENDPOINT : https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/token`
`GPM_OIDC_INTROSPECTION_ENDPOINT :  https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/token/introspect`
`GPM_OIDC_USERINFO_ENDPOINT : https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/userinfo`
`GPM_OIDC_END_SESSION_ENDPOINT : https://keycloak.xyz.com/realms/<realm-name>/protocol/openid-connect/logout`
`GPM_OIDC_CLIENT_ID : <client_id_configured_in_keycloak>`
`GPM_OIDC_CLIENT_SECRET : <client_secret_from_keycloak>`

@ralgozino Above are the env vars set.

**Comment by goku007xx** [comment]
Yes, we are using `alb.ingress.kubernetes.io/certificate-arn` annotation for AWS alb to use a SSL certificate. HTTPS is working in all requests except that specific logout request. My guess is that `flask.request.url` for logout gives the url as a http url.

**Comment by ralgozino** [comment]
Hi @goku007xx 
Thanks for the details, I was able to replicate the problem and we just merged a fix. It will be included in 1.0.5 which is to be released soon when we fix #728
