### ISSUE TITLE
OIDC broken in v1.0.5

### ISSUE THREAD

**Issue by ltwongaa** [sighupio/gatekeeper-policy-manager#759]
Due to BaseSettings is moved from pydantic to pydantic_settings
oic 1.6.0 has issue on importing it from wrong package
and it is fixed in oic 1.6.1
https://github.com/CZ-NIC/pyoidc/releases/tag/1.6.1
https://github.com/CZ-NIC/pyoidc/pull/862

The latest version Flask-pyoidc 3.14.0 used by GPM is using oic 1.6.0
so GPM has the issue as well
There is a related issue created in Flask-pyoidc with more detail
https://github.com/zamzterz/Flask-pyoidc/issues/163

Apologize that I am not able to copy the error log here due to restriction

**Comment by ltwongaa** [comment]
Hi @ralgozino ,

it make sense to my case.
I rebuild the image with tag v1.0.5 in my local to remove some pem files that triggers cyber alerts,
so I am using a different version of pydantic compare to the original v1.0.5 image.

Thanks!

**Comment by ralgozino** [comment]
Oh, I see.. just pin pydantic to 1.x adding it to the constraints.txt file like this:

https://github.com/sighupio/gatekeeper-policy-manager/commit/756019be888c9af2d2d561674ef2f4c9d8a76f8f

And you should be good.

We'll bump the depencies and switch to pydantic v2 soon
