### ISSUE TITLE
Multi-cluster context intermittently displaying incorrect content

### ISSUE THREAD

**Issue by Markieta** [sighupio/gatekeeper-policy-manager#827]
When opening multiple tabs/windows of GPM in different contexts, some tabs/windows will display content of a different (incorrect) context. The URL and selected context (from the drop-down menu) do not change when this occurs.

The following screenshot depicts cluster contexts `legacy-dev` and `legacy-prod` having the exact same set of constraints/violations (both displaying `legacy-prod` content). Refreshing the `legacy-dev` tab and waiting a few seconds for the constraints to update accordingly resolves this.

![Screenshot from 2023-08-24 13-22-18](https://github.com/sighupio/gatekeeper-policy-manager/assets/3028095/dab02b01-92fd-483a-94ce-f91bf694ffc5)

**Comment by ralgozino** [comment]
Hi Christopher!

Thanks for the report, while I try to replicate the issue can I ask you to try with the `go` tag? It uses the new backend written in go, I suspect the problem is how we use the browser storage to keep the state for the frontend, but I think it's worth trying.

**Comment by ralgozino** [comment]
No need to test the Go backend, I was able to replicate the problem with both the Python and the Go backends. I'm 99% sure that the issue is how we store the selected context in the frontend.

**Comment by Markieta** [comment]
I haven't been able to pinpoint where in the source code this is happening.

I did notice when this issue does occur, in Chrome's **Network** tab I see it's loading multiple contexts:

![gpm-network](https://github.com/sighupio/gatekeeper-policy-manager/assets/3028095/6ef7df1d-a974-4de4-bf65-173eec98d830)
![Screenshot from 2023-08-30 00-31-26](https://github.com/sighupio/gatekeeper-policy-manager/assets/3028095/1a6a0949-03ea-44d4-9279-df798b4465f9)

**Comment by ralgozino** [comment]
Hi @Markieta !

Would you mind testing with the image `quay.io/sighup/gatekeeper-policy-manager:286f0d0a2a33a77bf10ca3138d453d5a536e408f` (built from the linked PR) if that fixes the issue for you?

thanks in advance

**Comment by Markieta** [comment]
Yup, works great. Thanks for the fix!

**Comment by ralgozino** [comment]
awesome, thanks for the feedback!
